-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 14:38:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comap_cvc_usuario` DEFAULT CHARACTER SET utf8 ;
USE `comap_cvc_usuario` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `pesquisador` VARCHAR(50) NULL,
  `supervisor` VARCHAR(50) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tb_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_veiculos` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `auto` INT NULL,
  `motos` INT NULL,
  `onibus` INT NULL,
  `caminhao` INT NULL,
  `date` VARCHAR(25) NULL,
  `time` VARCHAR(25) NULL,
  `tb_usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  CONSTRAINT `fk_tb_veiculos_tb_usuarios`
    FOREIGN KEY (`tb_usuarios_id_usuario`)
    REFERENCES `comap_cvc_usuario`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tb_usuarios (pesquisador,supervisor) value ("teste","teste");

select * from tb_veiculos;
select * from tb_usuarios;

truncate tb_usuarios;
            
SET foreign_key_checks = 0;
SET foreign_key_checks = 1;

drop table tb_veiculos;
drop database comap_cvc_usuario;
