-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 14:38:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comap_cvc_usuario` DEFAULT CHARACTER SET utf8 ;
USE `comap_cvc_usuario` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL,
  `senha` VARCHAR(32) NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;
INSERT INTO tb_login(usuario,senha) VALUES ("administrador", md5("comapcvc"));

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_veiculos_9e36UtiCam2L` (
	`id_veiculo_9e36UtiCam2L` INT NOT NULL AUTO_INCREMENT,
	`auto` INT NULL,
	`utilitario` INT NULL,
	`auto3E` INT NULL,
	`auto4E` INT NULL,
	`onibus2E` INT NULL,
	`onibus3E` INT NULL,
	`onibus4E` INT NULL,
	`veiculoOficial` INT NULL,
	`veiculoEspecial` INT NULL,
	`motos` INT NULL,
	`cLeve2E` INT NULL,
	`c2E` INT NULL,
	`c3R` INT NULL,
	`c31S` INT NULL,
	`c4R` INT NULL,
	`c41S` INT NULL,
	`c42S` INT NULL,
	`c5R` INT NULL,
	`c51S` INT NULL,
	`c52S` INT NULL,
	`c6R` INT NULL,
	`c61S` INT NULL,
	`c62S` INT NULL,
	`c63S` INT NULL,
	`c7R` INT NULL,
	`c71S` INT NULL,
	`c72S` INT NULL,
	`c73S` INT NULL,
	`c8R` INT NULL,
	`c81S` INT NULL,
	`c82S` INT NULL,
	`c83S` INT NULL,
	`c84S` INT NULL,
	`c9R` INT NULL,
	`c91S` INT NULL,
	`c92S` INT NULL,
	`c93S` INT NULL,
	`c94S` INT NULL,
	`date` VARCHAR(25) NULL,
	`time` VARCHAR(25) NULL,
	`transito` VARCHAR(25) NULL,
	`sigapare` VARCHAR(25) NULL,
	`chuva` VARCHAR(25) NULL,
	`latitude` VARCHAR(25) NULL,
	`longitude` VARCHAR(25) NULL,
	`tb_usuarios_id_usuario_9e36UtiCam2L` INT NOT NULL,
  PRIMARY KEY (`id_veiculo_9e36UtiCam2L`),
  CONSTRAINT `fk_tb_veiculos_tb_usuarios_9e36UtiCam2L`
    FOREIGN KEY (`tb_usuarios_id_usuario_9e36UtiCam2L`)
    REFERENCES `comap_cvc_usuario`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_projetos` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id_projeto`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_config_projeto` (
  `id_config_projeto` INT NOT NULL AUTO_INCREMENT,
  `rodovia` VARCHAR(100) NULL,
  `km` VARCHAR(100) NULL,
  `posto` VARCHAR(100) NULL,
  `sentido` VARCHAR(100) NULL,
  `dataInicio` VARCHAR(100) NULL,
  `dataFim` VARCHAR(100) NULL,
  `tb_projetos_id_projeto` INT NOT NULL,
  PRIMARY KEY (`id_config_projeto`),
   CONSTRAINT `fk_tb_config_projeto_tb_projetos`
    FOREIGN KEY (`tb_projetos_id_projeto`)
    REFERENCES `comap_cvc_usuario`.`tb_projetos` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `pesquisador` VARCHAR(50) NULL,
  `supervisor` VARCHAR(50) NULL,
  `idDevice` VARCHAR(50) NULL,
  `tb_config_projeto_id_projeto` INT NOT NULL,
	PRIMARY KEY (`id_usuario`),
	CONSTRAINT `fk_tb_config_tb_usuarios`
	FOREIGN KEY (`tb_config_projeto_id_projeto`)
	REFERENCES `comap_cvc_usuario`.`tb_config_projeto` (`id_config_projeto`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tb_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_veiculos` (
	`id_veiculo` INT NOT NULL AUTO_INCREMENT,
	`contagem` LONGTEXT NULL,
	`tb_usuarios_id_usuario` INT NOT NULL,
	`tb_formularios_id_formulario`INT NOT NULL,
    `tb_config_projeto_id_posto_sentido` INT NOT NULL,
	PRIMARY KEY (`id_veiculo`),
	CONSTRAINT `fk_tb_veiculos_tb_usuarios`
	FOREIGN KEY (`tb_usuarios_id_usuario`)
	REFERENCES `comap_cvc_usuario`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
	ON UPDATE NO ACTION,
    CONSTRAINT `fk_tb_veiculos_tb_formularios`
    FOREIGN KEY (`tb_formularios_id_formulario`)
    REFERENCES `comap_cvc_usuario`.`tb_formularios` (`id_formulario`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_tb_config_projeto_id_posto_sentido`
	FOREIGN KEY (`tb_config_projeto_id_posto_sentido`)
	REFERENCES `comap_cvc_usuario`.`tb_config_projeto` (`id_config_projeto`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_formularios` (
  `id_formulario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id_formulario`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_botoes` (
  `id_botao` INT NOT NULL AUTO_INCREMENT,
  `nome_botao` VARCHAR(25) NULL,
  `nome_relatorio` VARCHAR(25) NULL,
  `qtd_eixos` INT NULL,
  `qtd_suspensos` INT NULL,
  `seq_tablet` INT NULL,
  `seq_relatorio` INT NULL,
  `cor` VARCHAR(25) NULL,
  `tb_formularios_id_formulario` INT NOT NULL,
  PRIMARY KEY (`id_botao`),
  CONSTRAINT `fk_tb_botoes_tb_formularios`
    FOREIGN KEY (`tb_formularios_id_formulario`)
    REFERENCES `comap_cvc_usuario`.`tb_formularios` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `comap_cvc_usuario`.`tb_tablets` (
  `id_tablet` INT NOT NULL AUTO_INCREMENT,
  `tablet` VARCHAR(100) NULL,
  `senha` VARCHAR(32) NULL,
  `tb_projetos_id_projeto` INT NOT NULL,
  `tb_formularios_id_formulario` INT NOT NULL,
  PRIMARY KEY (`id_tablet`),
  CONSTRAINT `fk_tb_tablets_tb_projetos`
    FOREIGN KEY (`tb_projetos_id_projeto`)
    REFERENCES `comap_cvc_usuario`.`tb_config_projeto` (`id_config_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_tb_tablets_tb_formularios`
    FOREIGN KEY (`tb_formularios_id_formulario`)
    REFERENCES `comap_cvc_usuario`.`tb_formularios` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

UPDATE tb_botoes
SET cor = 'tertiary'
WHERE id_botao = 4;

SELECT * FROM tb_config_projeto v 
            JOIN tb_projetos u ON v.tb_projetos_id_projeto = u.id_projeto
            JOIN tb_tablets t ON v.id_config_projeto = t.tb_projetos_id_projeto
            JOIN tb_botoes b ON t.tb_formularios_id_formulario = b.tb_formularios_id_formulario
            WHERE t.tb_formularios_id_formulario = 2;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE `comap_cvc_usuario` ;

INSERT INTO tb_formularios(nome) VALUES('TESTE');

INSERT INTO tb_botoes(nome_botao,nome_relatorio,qtd_eixos,qtd_suspensos,seq_tablet,seq_relatorio,cor,tb_formularios_id_formulario) 
	VALUES('Caminhao','CAMINHAO',0,0,1,1,'terceary',2);
    
INSERT INTO tb_tablets (tablet,senha,tb_projetos_id_projeto,tb_formularios_id_formulario) values("tablet1",md5("tablet1"),1,1);


SELECT * FROM tb_veiculos v 
        JOIN tb_usuarios u ON v.tb_usuarios_id_usuario = u.id_usuario
        JOIN tb_config_projeto c ON u.tb_config_projeto_id_projeto = c.id_config_projeto
        WHERE v.id_veiculo = 7;
        
SELECT * FROM tb_botoes WHERE tb_formularios_id_formulario = 1;

delete from tb_veiculos where id_veiculo = 6;
        
delete from tb_projetos where id_projeto = 2;

select * from tb_usuarios;
select * from tb_veiculos;
select * from tb_projetos;
select * from tb_tablets;
select * from tb_config_projeto;
select * from tb_veiculos_9e36UtiCam2L;
select * from tb_formularios;
select * from tb_botoes;
select * from tb_login;
SELECT * FROM tb_config_projeto WHERE id_config_projeto= 3 ORDER BY sentido;
SELECT * FROM tb_veiculos v 
			JOIN tb_usuarios u ON v.tb_usuarios_id_usuario = u.id_usuario
			JOIN tb_config_projeto c ON u.tb_config_projeto_id_projeto = c.id_config_projeto
			WHERE v.id_veiculo = 1;

SELECT * FROM tb_veiculos v 
			JOIN tb_usuarios u ON v.tb_usuarios_id_usuario = u.id_usuario
			JOIN tb_config_projeto c ON u.tb_config_projeto_id_projeto = c.id_config_projeto
			WHERE c.id_config_projeto = 2;

SELECT idDevice FROM tb_usuarios WHERE id_usuario = 1;

SELECT SUM(auto) AS Total FROM tb_veiculos_9e36UtiCam2L v 
			JOIN tb_usuarios u
			ON v.tb_usuarios_id_usuario_9e36UtiCam2L = u.id_usuario
			WHERE u.id_usuario = 25;

select sum(auto)  from tb_veiculos_9e36uticam2L;

SET foreign_key_checks = 0;
SET foreign_key_checks = 1;





















-- delete from tb_projetos where id_projeto = 5;

-- truncate tb_usuarios;
-- truncate tb_veiculos;
-- truncate tb_projetos;
-- truncate tb_tablets;
-- truncate tb_config_projeto;
-- truncate tb_veiculos_9e36uticam2L;
-- truncate tb_botoes;
-- truncate tb_formularios;
